# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Archi-veD'
tagline:          'by Jonghyeok Han'
description:      'An archive of my studies, dev logs, and tutorials.'
url:              https://ookk2007.github.io
baseurl:          ''

author:
  name:           'Jonghyeok Han'
  url:            https://github.com/ookk2007

plugins:
  - jekyll-paginate
  - jekyll-gist

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ookk2007
