# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Archi-veD
tagline:          by Jonghyeok Han
description:      'An archive of my <a href="/category/learning">learning</a>, <a href="/category/dev-log">dev logs</a>, and <a href="/category/tutorial">tutorials</a>.'
url:              https://ookk2007.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Jonghyeok Han'
  github:         https://github.com/ookk2007
  email:          ookk2007@naver.com
  youtube:        https://www.youtube.com/@hanjeok1

remote_theme: fongandrew/hydeout
excerpt_separator: <!--more-->

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

version: 1.0.0